/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

int32_t add_numbers(int32_t x, int32_t y);
int32_t sub_numbers(int32_t x, int32_t y);
int32_t mul_numbers(int32_t x, int32_t y);
int32_t div_numbers(int32_t x, int32_t y);


int main(void)
{


	int32_t res, x, y;

	x = 10;
	y = -30;

	res = add_numbers(x, y);
	printf("%d add %d res : %d \n",x , y, res);

	res = sub_numbers(x, y);
	printf("%d sub %d res : %d \n",x , y, res);

	res = mul_numbers(x, y);
	printf("%d mul %d res : %d \n",x , y, res);

	res = div_numbers(x, y);
	printf("%d div %d res : %d \n",x , y, res);
	/* Loop forever */
	for(;;);
}


__attribute__((naked)) void SVC_Handler(void)
{
	__asm("MRS R0, MSP");
	__asm("B SVC_Handler_c");
}

void SVC_Handler_c(uint32_t *pBaseOfStackFrame)
{
	printf("in SVC handler\n");

	int32_t arg0, arg1, res;

	uint8_t *pReturn_addr = (uint8_t*)pBaseOfStackFrame[6];
	pReturn_addr-=2;

	uint8_t svc_number = *pReturn_addr;

	arg0 = pBaseOfStackFrame[0];
	arg1 = pBaseOfStackFrame[1];

	switch(svc_number)
	{
	case(36):
			res = arg0 + arg1;
			break;
	case(37):
			res = arg0 - arg1;
			break;
	case(38):
			res = arg0 * arg1;
			break;
	case(39):
			res = arg0 / arg1;
			break;
	default:
		printf("invalid svc code\n");

	}

	pBaseOfStackFrame[0] = res;
}

int32_t add_numbers(int32_t x, int32_t y)
{
	int32_t res;
	__asm("SVC #36");
	__asm("MOV %0, R0":"=r"(res)::);
	return res;
}

int32_t sub_numbers(int32_t x, int32_t y)
{
	int32_t res;
	__asm("SVC #37");
	__asm("MOV %0, R0":"=r"(res)::);
	return res;
}

int32_t mul_numbers(int32_t x, int32_t y)
{
	int32_t res;
	__asm("SVC #38");
	__asm("MOV %0, R0":"=r"(res)::);
	return res;
}

int32_t div_numbers(int32_t x, int32_t y)
{
	int32_t res;
	__asm("SVC #39");
	__asm("MOV %0, R0":"=r"(res)::);
	return res;
}
