/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define USART3_IRQNO 39

int main(void)
{

	//2. 啟用NVIC中 USART3 IRQ number
	uint32_t *pISER1 = (uint32_t)0XE000E104;
	*pISER1 |= (1 << (USART3_IRQNO % 32));

    //1. 手動設置pend，設置USART3的pending bit
	uint32_t *pISPR1 = (uint32_t)0XE000E204;
	*pISPR1 |= (1 << (USART3_IRQNO % 32));


	for(;;);
}


void USART3_IRQHandler(void)
{
	printf("in USART3 isr\n");
}
