/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


//1. enable fault
//2. implement exception handler
//3. generate fault
//4. analyze

int main(void)
{
	// System Handler Control and State Register
	uint32_t *pSHCRS = (uint32_t*)0xE000ED24;

	//18th bit usage fault,17:bus, 16:memory fault
	*pSHCRS |= (1 << 18);
	*pSHCRS |= (1 << 17);
	*pSHCRS |= (1 << 16);

	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFFFF;
	void (*pFunc)(void);
	pFunc = (void*)(0x20010001);
	pFunc();

	for(;;);

}

__attribute__((naked)) void UsageFault_Handler(void){
	__asm ("MRS R0, MSP");
	__asm ("B UsageFault_Handler_c");
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame){
	//UFSR indicates reason why causes fault
	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;

	printf("in usage fault handler\n");
	printf("UFSR: %lx \n", (*pUFSR) & 0xFFFF);

	printf("BaseStackFrame : %lx \n", pBaseStackFrame);
	printf("R0 : %lx \n", pBaseStackFrame[0]);
	printf("R1 : %lx \n", pBaseStackFrame[1]);
	printf("R2 : %lx \n", pBaseStackFrame[2]);
	printf("R3 : %lx \n", pBaseStackFrame[3]);
	printf("R12 : %lx \n", pBaseStackFrame[4]);
	printf("LR : %lx \n", pBaseStackFrame[5]);
	printf("PC : %lx \n", pBaseStackFrame[6]);
	printf("XPSR : %lx \n", pBaseStackFrame[7]);

	for(;;);
}

void HardFault_Handler(void)
{
	printf("Exception : Hardfault\n");
	while(1);
}


void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}
